---
title: "Believers vs NonBelievers"
author: "Elizabeth Hiroyasu"
date: "October 14, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
library(survey)
library(weights)
library(anesrake)
library(lmtest)
library(sandwich)
library(car)
library(psych)

grizz <- read.csv("GRIZZLY_DATA_USE.csv", header = T)
```

## Weighting the data
```{r, echo=FALSE}
# Create dummy for highet_degree and urban_rural so I can weight according to whether 
# someone is (not) rural and whether they (don't) have college degree. This is jsut a 
# formality type thing to make the weighting process go more smoothly. 

grizz$college <- grizz$highest_degree>=5 
grizz$rural <- grizz$urban_rural==3

# Here I isolate percent of respondents falling into each category. This is so I have 
# a rough estimate of distribution of respondents. 

wpct(grizz$gender)
wpct(grizz$urban_rural)
wpct(grizz$latino)
wpct(grizz$highest_degree)
wpct(grizz$college)
wpct(grizz$rural)

# wpct produces a table of the proportion of data in each category for any variable.

# Here I use US Census data to make variables with distribution of each data for all of 
# California. 

gender <- c(.50, .50)
rural <- c(.13, .87) # Rural; non-rural.
latino <- c(.39, .61) # Latino; not-latino.
college <- c(.32, .68) # BA/higher; no college degree.  

# Here I put the census variables into a list and name them. This is so they can be called 
# upon later and used for weighting. Essentially, they are population-level estiamtes for 
# all of California and are what we weight to. 

targets <- list(gender, rural, latino, college)
names(targets) <- c("gender", "rural", "latino", "college")

# Here I create unique ids for all complete observations in the dataframe, and then determine
# which variables should be used to weight based on the ones I provide in "target" list. 

grizz$caseid <- 1:length(grizz$good_complete) # Create unique id for each complete obs. 
anesrakefinder(targets, grizz, choosemethod="total") 

# Here I rake weights data. This process determines how variables should be weighted and then rakes the
# data to develop weights for the variables so that they match the target values I provided. 

newgrizz <- anesrake(targets, grizz, caseid = grizz$caseid,
                     verbose=F, cap=5, choosemethod = "total",
                     type="pctlim", pctlim=.05, nlim=5, iterate=T, force1=T)

# Here I create a new dataframe with weighted data #

wt_grizz_df <- svydesign(ids = ~1, data = grizz, weights = newgrizz$weightvec) 

```

##Believers vs NonBelievers

```{r, echo=FALSE, warning=FALSE}
grizz_wt<-newgrizz$dataframe

ggplot(grizz_wt) + 
  geom_bar(aes(species_griz),bins = 3, width=1,  fill = c("darkgreen", "firebrick4", "sienna4"), colour = "black") +
  labs(x = "Response", y = "Frequency",title = "Do Grizzly Bears Exist in California") +
  scale_x_continuous(breaks = 1:3, labels = c("Yes", "No", "Don't Know")) + 
  theme(panel.border = element_rect(linetype = "solid", colour = "black", fill = NA))


believers<-(grizz[which(grizz_wt$species_griz==1),])
nonbelievers<-(grizz[which(grizz_wt$species_griz==2),])
dontknow<-(grizz[which(grizz_wt$species_griz==3),])
lowknowledge<-rbind(nonbelievers, dontknow)
```

##Factor analysis
```{r, echo=FALSE}
believe_factor<-cbind(believers[,47:61])
nonbelieve_factor<-cbind(nonbelievers[,47:61])
dontknow_factor<-cbind(dontknow[,47:61])
lowknowledge_factor<-cbind(lowknowledge[,47:61])

names(believe_factor)<-c("survival", "forests", "SafetyThreat", "LivelihoodThreat",
                         "Tourism", "Feds", "ThreatPP", "OtherSpecies", "Extinction",
                         "LocalControl", "Ranchers", "OutdoorRec", "Ag", "Urban", "Rural")

names(nonbelieve_factor)<-c("survival", "forests", "SafetyThreat", "LivelihoodThreat",
                            "Tourism", "Feds", "ThreatPP", "OtherSpecies", "Extinction",
                            "LocalControl", "Ranchers",
                            "OutdoorRec", "Ag", "Urban", "Rural")

names(dontknow_factor)<-c("survival", "forests", "SafetyThreat", "LivelihoodThreat",
                            "Tourism", "Feds", "ThreatPP", "OtherSpecies", "Extinction",
                            "LocalControl", "Ranchers",
                            "OutdoorRec", "Ag", "Urban", "Rural")

names(lowknowledge_factor)<-c("survival", "forests", "SafetyThreat", "LivelihoodThreat",
                            "Tourism", "Feds", "ThreatPP", "OtherSpecies", "Extinction",
                            "LocalControl", "Ranchers",
                            "OutdoorRec", "Ag", "Urban", "Rural")
```

#Believers
```{r, echo=FALSE}
believe_comp<-factanal(believe_factor, 5, scores="Bartlett")
believe_comp

#Plotting the relationship of the factors
fa.diagram(believe_comp$loadings)
```

#NonBelievers
```{r, echo=FALSE}
nonbelieve_comp<-factanal(nonbelieve_factor, 5, scores="Bartlett")
nonbelieve_comp

#Plotting the relationship of the factors
fa.diagram(nonbelieve_comp$loadings)
```

#Don't Know
```{r, echo=FALSE}
dontknow_comp<-factanal(dontknow_factor, 5, scores="Bartlett")
dontknow_comp

#Plotting the relationship of the factors
fa.diagram(dontknow_comp$loadings)
```

#Low Knowledge
```{r, echo=FALSE}
lowknowledge_comp<-factanal(lowknowledge_factor, 5, scores="Bartlett")
lowknowledge_comp

#Plotting the relationship of the factors
fa.diagram(lowknowledge_comp$loadings)
```